ISQA3900_Group11/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('mavSlice.urls')),

]

mavSlice/urls.py
# from django.conf.urls import url
from . import views
from django.urls import path, re_path
from django.conf.urls.static import static
from django.conf import settings

# from django.conf.urls import url
# from mysite.core import views as core_views

app_name = 'mavSlice'

urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    re_path(r'^Cart/$', views.cart_detail, name='Cart'),
    path('Menu/WholePies/', views.Menu, name='Menu'),
    path('Menu/Slice/', views.slice_Menu, name='slice_Menu'),
    path('Cart/', views.cart_detail, name='cart_detail'),
    path('add/<str:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<str:product_id>/', views.cart_remove, name='cart_remove'),
    path('custom/', views.custom, name='custom'),
    path('signup/', views.signup, name='signup'),
    path('Cart/order_confirmation/', views.payment_completed, name='order_confirmation'),
    path('checkout/', views.checkout, name='checkout'),
    # path('user/<int:pk>/summary/', views.user_info, name='user_info'),
    # path('user/<int:pk>/summary/delivery/', views.user_info_delivery, name='user_info_delivery'),
    # path('user/<int:pk>/summary/payment/', views.user_info_payment, name='user_info_payment'),
    path('place_order/', views.order_create, name='order_create'),
    path('admin/order/<str:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('Menu/<str:product_id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('create/payment/process/', views.payment_process, name='process_payment'),
    path('complete/', views.payment_completed, name='complete_payment'),
    path('canceled/', views.payment_canceled, name='payment_canceled'),
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<str:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<str:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mavSlice/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import *
from django.contrib.auth.models import User


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'price', 'image')


# class Registration(UserCreationForm):
#     email = forms.EmailField(required=True)


# class UserForm(forms.ModelForm):
#     class Meta:
#         model = User
#         #fields = ('username', 'fname', 'lname', 'email', 'password1', 'password2', )
#         fields = ('first_name', 'last_name', 'email')

# class CustomerForm(forms.ModelForm):
#     class Meta:
#         model = customer
#         fields = ('cust_fname', 'cust_lname', 'cust_password', 'delivery_info','payment_info')


# def save(self, commit=True):
#     customer = super(Registration, self).save(commit=False)
#     customer.fname = self.cleaned_data['fname']
#     customer.lname = self.cleaned_data['lname']
#     #customer.email = self.cleaned_data['email']
#
#    if commit:
#        User.save()
#        customer.save()
#        return customer


# NOT FINISHED
# class OrdersForm(forms.ModelForm):
#     class Meta:
#         model = Order
#         fields = ('coupon', 'order_price', 'delivery', 'placed_time')
class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'state',
                  'city', 'zip',]


# NOT FINISHED
class CouponForm(forms.ModelForm):
    class Meta:
        model = Coupon
        fields = ('totalDiscount',)


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


# class DeliveryForm(forms.ModelForm):
#     class Meta:
#         model = Delivery
#         fields = ('street_address', 'street_address2', 'city', 'state', 'zipCode')


# Not finished, payment info?,
# class signupForm(UserCreationForm):
    # delivery_info = forms.ModelForm()
    # payment_info = forms.ModelForm()
    # delivery_info = forms.ModelForm()

class User(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'password1',)

mavSlice/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from django.template.loader import render_to_string
from .models import *
from .forms import *
from .cart import *
from .forms import *
import braintree
from django.core.mail import send_mail
from django.conf import settings


# import weasyprint


# Menu Functionality
def Menu(request):
    products = Product.objects.filter(type__exact='Whole Pie')
    return render(request, 'mavSlice/Menu.html', {'products': products})


def slice_Menu(request):
    products = Product.objects.filter(type__exact='Slice')
    return render(request, 'mavSlice/slice_Menu.html', {'products': products})


def get_products():
    return Product.objects.filter(created_date__lte=timezone.now())


def home(request):
    return render(request, 'mavSlice/home.html',
                  {'Home': home})


def custom(request):
    return render(request, 'mavSlice/custom.html',
                  {'custom': custom})


# Cart Functionality
def Cart_view(request):
    # price_all = Decimal(calculate_cart_price(request.user))
    # context = {}
    # context.update ({"price_all": price_all})
    # context.update({"Pizza": Product.objects.filter(add_by=request.user).filter(already_ordered=False)})
    return render(request, 'mavSlice/Cart.html',
                  {'Cart': Cart_view})


# Context Processor
# May need its own .py file
def cart(request):
    return {'cart': Cart(request)}


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, product_id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect(reverse('mavSlice:cart_detail'))


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, product_id=product_id)
    cart.remove(product)
    return redirect(reverse('mavSlice:Cart'))


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'mavSlice/Cart.html', {'cart': cart})


def product_detail(request, product_id, slug):
    product = get_object_or_404(Product, product_id=product_id, product_slug=slug)
    cart_product_form = CartAddProductForm()
    return render(request, 'mavSlice/product_detail.html',
                  {'product': product, 'cart_product_form': cart_product_form})


def product_list(request):
    products = Product.objects
    print(str(products))


# def signup(request):
#     if not request.user.is_authenticated:
#         if request.method == "POST":
#             form = Registration(request.POST)
#             if form.is_valid():
#                 form.save()
#                 username = form.cleaned_data["username"]
#                 password = form.cleaned_data["password1"]
#                 user = authenticate(username=username, password=password)
#                 login(request, user)
#                 return redirect("mavSlice:home")
#         else:
#             form = Registration()
#         context = {"form": form}
#         return render(request, 'registration/signup.html', context)
#     else:
#         return redirect("mavSlice:home")

# def signup(request):
#     return render(request, 'registration/signup.html',
#                   {'signup': signup})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('mavSlice:home')
    else:
        form = UserCreationForm()
    return render(request, 'mavSlice/signup.html', {'form': form})


def login_view(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = AuthenticationForm(data=request.POST)
            if form.is_valid():
                username = form.cleaned_data["username"]
                password = form.cleaned_data["password"]
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    if next is not None:
                        return redirect("mavSlice:home")
                    else:
                        return redirect("mavSlice:home")
        else:
            form = AuthenticationForm()
        context = {"form": form}
        return render(request, 'registration/login.html', context)
    else:
        return redirect("mavSlice:home")


def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect("mavSlice:home")


# Order Functionality
# def order_create(request):
#     cart = Cart(request)
#     if request.method == 'POST':
#         form = OrdersForm(request.POST)
#         if form.is_valid():
#             order = form.save()
#             for product in cart:
#                 OrderProduct.objects.create(order=order, product=product['product'], price=product['price'],
#                                             quantity=product['quantity'])
#             # clear the cart
#             cart.clear()
#             # set the order in the session
#             request.session['order_id'] = order.order_id
#             # redirect for payment
#             return redirect(reverse('mavSlice:process_payment'))
#
#     else:
#         form = OrdersForm()
#     return render(request,
#                   'mavSlice/checkout.html',
#                   {'cart': cart, 'form': form})


@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('mavSlice/Order/pdf.html',
                            {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename=\
        "order_{}.pdf"'.format(order.id)
    weasyprint.HTML(string=html).write_pdf(response,
                                           stylesheets=[weasyprint.CSS(
                                               settings.STATIC_ROOT + 'css/pdf.css')])
    return response


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request,
                  'admin/admin_order_detail.html',
                  {'order': order})


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'],
                                         quantity=item['quantity'])
            # clear the cart
            cart.clear()
            # set the order in the session
            request.session['order_id'] = order.order_id

            # Send confirmation email
            subject = 'MavSlice Order Number {} Has Been Placed'.format(order.order_id)
            message = 'Thank you {} for placing an order with MavSlice today.\n' \
                      'In hope to see you again, here is all of our current Coupons:\n{}\n' \
                      'Hope to see you again!'.format(order.first_name, Coupon.objects.all())
            try:
                send_mail(subject, message, 'mavSliceGroup11@gmail.com', [order.email])
                print('Email successfully sent')
            except:
                print('Error: Email not sent')
            # redirect for payment
            return redirect(reverse('mavSlice:process_payment'))

    else:
        form = OrderCreateForm()
    return render(request,
                  'mavSlice/Order/create.html',
                  {'cart': cart, 'form': form})


@login_required
def checkout(request):
    return render(request, 'mavSlice/checkout.html',
                  {'Checkout': checkout})


def payment_process(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, order_id=order_id)

    if request.method == 'POST':
        # retrieve nonce
        nonce = request.POST.get('payment_method_nonce', None)
        # create and submit transaction
        result = braintree.Transaction.sale({
            'amount': '{:.2f}'.format(order.get_total_cost()),
            'payment_method_nonce': nonce,
            'options': {
                'submit_for_settlement': True
            }
        })
        if result.is_success:
            # mark the order as paid
            order.paid = True
            # store the unique transaction id
            order.braintree_id = result.transaction.id
            order.save()
            return redirect('mavSlice:complete_payment')
        else:
            return redirect('mavSlice:payment_canceled')
    else:
        # generate token
        client_token = braintree.ClientToken.generate()
        return render(request, 'mavSlice/payment/process_payment.html', {'order': order, 'client_token': client_token})


def payment_completed(request):
    return render(request, 'mavSlice/payment/payment_complete.html')


def payment_canceled(request):
    return render(request, 'mavSlice/payment/payment_cancelled.html')

mavSlice/templates/mavSlice/Cart.html
{% extends "mavSlice/base.html" %}
{% load static %}

{% block title %}
  Your shopping cart
{% endblock %}
<link rel="stylesheet" href="{% static "css/stylesheet.css" %}">
{% block content %}
  <h1>Your Cart</h1>

  <table class="cart">
    <thead>
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url "mavSlice:cart_add" product.product_id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Update">
                {% csrf_token %}
              </form>
            </td>
            <td><a href="{% url "mavSlice:cart_remove" product.product_id %}">Remove</a></td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>

    <style>
      table{
        width:150%;
        border-spcaing:0;
        border-collapse: collapse;
    }
    table th, table td{
        text-align:left;
    font-size:14px;
    padding:10px;
    margin:0;
    }

    tbody tr:nth-child(odd) {
    background:#efefef;}

    thead th, tbody tr.total{
        background:lightblue;
        color:#fff;
        font-weight:bold;

    }

    table.cart{
        margin-bottom:40px;
    }
    table.cart img{
        width:180px;
    }

    tbody td.num{
        text-align:right;
    }
    td input[type="submit"] {
    font-size:12px;
    padding:4px 10px;}

    h1{
        padding:10px 100px;
        font-size:30px;
        overflow:auto;
        font-family: 'Ubuntu', sans-serif;
        float:right;
        color:#333;


    }

    .button3{
        position:absolute;
        text-align: center;
    top:95%;
    left:10%;
    tranform:translate(-50%, -50%);
    background-color: palegoldenrod;
    width:100px;
    position:absolute;
    height:50px;
    border-radius:40px;
    border:2px; solid:#A2D9CE;
    transition: background-color 1s
    }

    .button3:hover{
    background-color: #A2D9CE;
}
    .button4{
        position:absolute;
        text-align: center;
    top:95%;
    left:120%;
    tranform:translate(-50%, -50%);
    background-color: palegoldenrod;
    width:100px;
    position:absolute;
    height:30px;
    border-radius:40px;
    border:2px; solid:#A2D9CE;
    transition: background-color 1s;

    }
    .button4:hover{
    background-color: #A2D9CE;

}

    </style>

    <a href="{% url "mavSlice:Menu" %}"
      <button class="button3">Continue shopping </button></a>
    <a href="{% url "mavSlice:order_create" %}"
      <button class="button4">Checkout</button>
      
    </a>

{% endblock %}

mavSlice/templates/mavSlice/Menu.html
<!DOCTYPE html>
<html lang="en">
{% extends 'mavSlice/base.html' %}
{% block content %}
{% load static %}
<style> body { background-color: beige; } </style>
<h1>MavSlice Whole Pizzas</h1>
    <div class="row" style="height:200px ; width:3000px;">
        <div class="col-md-4 d-flex align-items-stretch">
            {% for product in products %}
                <div class="card" style="width:1000rem ; height:10rem;">
                {% if product.image %}
                    <img src="{{ product.image.url }}" alt="product_pic">
                {% else %}
                    <img src="{% static "css/images/supreme.jpeg" %}" alt="no_prod_pic">
                {% endif %}

                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <h5 class="card-type">{{ product.type }}</h5>
                        <p><a class="btn btn-primary" href="{{ product.get_absolute_url }}"
                              role="button">Add to cart &raquo;</a></p>
                    </div>
                </div>
            {% endfor %}


    </div>
    </div>
{% endblock %}
</html>

mavSlice/templates/mavSlice/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

<link rel="stylesheet" href="{% static "css/stylesheet.css" %}">

<div class="container-fluid">

    <div class="navbar-header" href="   ">
        <!-- Logo -->

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark" id="myNavbar">

        <ul class="navbar-nav mr-auto">
{#            <li class="navbar-brand"></li>#}
{#            <li class="nav-item">#}
{#                <a class="nav-link" href="{% url 'mavSlice:home' %}">Home</a>#}
{#            </li>#}

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                     Menu
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'mavSlice:Menu' %}"><b><i>Whole Pizzas</i></b></a>
                    <a class="dropdown-item" href="{% url 'mavSlice:slice_Menu' %}">Single Slices</a>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'mavSlice:Cart' %}">Cart</a>
            </li>
        </ul>

        <ul class="nav navbar-nav mm-auto">
            <li class="nav-title">
                <a href="{% url 'mavSlice:home' %}"> <img src="/static/images/MavSliceLogo.png" alt="Logo" style="width:150px;"></a>
            </li>
        </ul>

        <ul class="nav navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li><a class="nav-link" href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-in"></span>Logout</a>
                </li>

            {% else %}
                <li><a class="nav-link" href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a>
                </li>
            {% endif %}
        </ul>
    </nav>


    </div>
        <body id="app-layout">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </body>
</div>

</html>

mavSlice/templates/mavSlice/cart_delivery.html
<!DOCTYPE html>
<html lang="en">
{% extends 'mavSlice/base.html' %}
{% block content %}
<style> body { background-color: beige; } </style>
<head>
    <meta charset="UTF-8">
    <title>Delivery</title>
</head>
<body>
This is the delivery page

</body>
{% endblock %}
</html>

mavSlice/templates/mavSlice/checkout.html
<!DOCTYPE html>
<html lang="en">
{% extends 'mavSlice/base.html' %}
{% block title %}
  Checkout
{% endblock %}

{% block content %}
<<<<<<< HEAD
    <link rel="stylesheet" href="{% static "css/stylesheet.css" %}">
=======
{% load static %}
    <link rel="stylesheet" href="{% static "css/stylesheet.css" %}">
    <style> body { background-color: beige; }

    </style>
  <h1>Checkout</h1>

  <div class="order-info">
    <h3>Your order</h3>
    <ul>
      {% for item in cart %}
        <li>
          {{ item.quantity }}x {{ item.product.name }}
          <span>${{ item.total_price }}</span>
        </li>
      {% endfor %}
    </ul>
    <p>Total: ${{ cart.get_total_price }}</p>


  </div>



  <form action="." method="post" class="order-form">
    {{ form.as_p }}
    <p><input type="submit" value="Place order"></p>
    {% csrf_token %}
  </form>



{% endblock %}
</html>

mavSlice/templates/mavSlice/checkout_confirmed.html
<!DOCTYPE html>
<html lang="en">
{% extends "mavSlice/base.html" %}

{% block title %}
  Thank you
{% endblock %}

{% block content %}

    <style> body { background-color: beige; } </style>
  <h1>Thank you</h1>
  <p>Your order has been successfully completed. Your order number is <strong>{{ order.order_id }}</strong>.</p>
    <p><strong>Go Mavs!</strong></p>
    <a class="nav-link" href="{% url 'mavSlice:Menu' %}">Keep Shopping!</a>
{% endblock %}
</html>

mavSlice/templates/mavSlice/custom.html
<!DOCTYPE html>
<html lang="en">
{% extends 'mavSlice/base.html' %}
{% block content %}
<style> body { background-color: beige; } </style>
<head>
    <meta charset="UTF-8">
    <title>Custom Pizza</title>
</head>
<body>
<h1>Show Checkboxes</h1>

<form action="/action_page.php">
  <input type="checkbox" id="vehicle1" name="vehicle1" value="Bike">
  <label for="vehicle1"> I have a bike</label><br>
  <input type="checkbox" id="vehicle2" name="vehicle2" value="Car">
  <label for="vehicle2"> I have a car</label><br>
  <input type="checkbox" id="vehicle3" name="vehicle3" value="Boat">
  <label for="vehicle3"> I have a boat</label><br><br>
  <input type="submit" value="Submit">
</form>

</body>
{% endblock %}
</html>

mavSlice/templates/mavSlice/customer_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'mavSlice/base.html' %}
{% block content %}

    <html>
    <head>
        <meta charset="UTF-8">
        <title>mavSlice</title>
    </head>
    <body class="bodylist">

    <div class="container">
        <div class="panel panel-primary">
            <div class="panel-heading">Welcome!</div>
            <div class="panel-body">
                Your perfect UNO Pizza Providor
            </div>
        </div>
    </div>
    <div class="row">
        <h2>Customer Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover w-auto">
            <thead>
            <tr class="bg-info">
                <th>Name</th>
                <th>Organization</th>
                <th>Role</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Bldg-Room</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip Code</th>

                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for customer in customers %}
                <tr>
                    <td>{{ customer.cust_name }}</td>
                    <td>{{ customer.organization }}</td>
                    <td>{{ customer.role }}</td>
                    <td>{{ customer.email }}</td>
                    <td>{{ customer.phone }}</td>
                    <td>{{ customer.bldgroom }}</td>
                    <td>{{ customer.address }}</td>
                    <td>{{ customer.city }}</td>
                    <td>{{ customer.state }}</td>
                    <td>{{ customer.zipcode }}</td>
                    <td><a href="{% url 'crm:customer_edit' pk=customer.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'crm:customer_delete' pk=customer.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>

                    <td><a href="{% url 'crm:summary' pk=customer.pk %}"
                           class="btn btn-primary">Summary</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    </body>
    </html>
{% endblock %}

</html>

mavSlice/templates/mavSlice/home.html
<!DOCTYPE html>
<html lang="en">
{% extends 'mavSlice/base.html' %}
{% block content %}
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="{% static "css/stylesheet.css" %}">
</head>
<body>

    <div class="container">
        {% if user.is_authenticated %}

            <h2 class="top-menu">Welcome to mavSlice {{ user.username }},</h2>

        {% else %}
            <p>Welcome to mavSlice Guest.</p>
        {% endif %}
    </div>
            <br>
            <br>

     <div class = "container5">
         <a href="{% url 'mavSlice:slice_Menu' %}">
                    <button class="btn5">Order Slice</button>
     </a>

      <a href="{% url 'mavSlice:Menu' %}">
                    <button class="btn6">Order Whole</button>
      </a>
     </div>

    <div class = "box">
        <div class="container1">
                    <img src="{% static "images/pizza.jpeg" %}" alt="pizza">
                    <a href="{% url 'mavSlice:Menu' %}">
                        <button class="btn1">Order Now !!</button>
                    </a>

        </div>


        <div class="container2">
                    <img src="{% static "images/pizza1.jpeg" %}">
                    <a href="{% url 'mavSlice:Menu' %}">
                        <button class="btn2">Order Now !!</button>
                    </a>

        </div>


    </div>




            <br>
            <br>
            <div class="container3">
                <h3>About US</h3>
                <p>mavSlice is a local pizza restaurant available on the campus. We love being the part of the campus and appreciate all our loyal customers. We use fresh ingredients to make our pizzas.</p>
            </div>

            <div class=" container4">

                <img src="{% static "images/img4.jpg" %}">

                <div class ="small">
                    <p>Get delicious fresh pizaa in a reasonable prices</p>

                    <p>

                        <a href="{% url 'mavSlice:Menu' %}">
                    <button class="btn3">Order Now!!</button>
                        </a>

                    </p>
            </div>

            </div>














</body>
{% endblock %}
</html>

mavSlice/templates/mavSlice/navigation.html
{% load base_extras %}
{% load static %}
<div id="topbar">
    <div class="navbar">
        <div class="navbar-side navbar-left"></div>
        <div class="navbar-content">
        {% if user.is_authenticated %}
            <a class="{% navactive request 'servers help_server' %}"
                href="{% url servers %}">Servers</a>

            <a class="{% navactive request 'account_clouds help_registeraccount
                href="{% url account_clouds %}">Cloud Accounts</a>

            <a class="{% navactive request 'account_details' %}"
                href="{% url account_details %}">User Profile</a>

            <a href="{% url auth_logout %}">Logout</a>
        {% else %}
            <a href="{% url auth_login %}">Login</a> or
            <a href="{% url registration_register %}"><b>Sign up</b></a>
        {% endif %}
        </div>
        <div class="navbar-side navbar-right"></div>
    </div>
</div>

mavSlice/templates/mavSlice/product_detail.html
<!DOCTYPE html>
<html lang="en">
{% extends 'mavSlice/base.html' %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}


{% block content %}
    <style> body { background-color: beige; } </style>
  <div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'images/No_image_available.png' %}{% endif %}">
    <h1>{{ product.name }}</h1>
    <h2><a href="{{ product.get_absolute_url }}">}</a></h2>
    <p class="price">${{ product.get_price }}</p>
    <form action="{% url "mavSlice:cart_add" product.product_id %}" method="post">
      {{ cart_product_form }}
      {% csrf_token %}
      <input type="submit" value="Add to cart">
    </form>
    {{ product.description|linebreaks }}

  <style>
      .product-detail{
            text-align:justify;}

      .product-detail img{
            width:40%;
            float:left;
            padding:0 20px 20px 0;}

      .product-detail h1{
          margin-bottom:0;
      }

      .product-detail h2{
          margin-top:10px;
      }

      .product-detail .price{
          color:#333;
          font-size:28px;
          font-weight:bold;
      }


  </style>
  </div>
{% endblock %}
</html>